name: Deploy On Senarc

on:
  repository_dispatch:
    types: [deploy_updated_workflow]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Deploy JDBotTester
      uses: JDJGInc/JDBotTester
      env:
        TOKEN: ${{ secrets.TOKEN }}
